export type CardType = 'INVITATION_CARD' | 'PAYMENT_CONFIRMATION_CARD' | 'QR_TICKET_CARD';

export interface CardTemplateInput {
  type: CardType;
  title: string;
  subtitle: string;
  guestName: string;
  eventName: string;
  eventDate?: string;
  venue?: string;
  amount?: string;
  linkLabel?: string;
  linkValue?: string;
  footer?: string;
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function buildCardSvg(input: CardTemplateInput): string {
  const lines = [
    input.eventDate ? `Date: ${input.eventDate}` : '',
    input.venue ? `Venue: ${input.venue}` : '',
    input.amount ? `Amount: ${input.amount}` : '',
    input.linkLabel && input.linkValue ? `${input.linkLabel}: ${input.linkValue}` : '',
    input.footer ?? '',
  ].filter(Boolean);

  const body = lines
    .map((line, index) => `<text x="60" y="${280 + index * 44}" fill="#334155" font-size="24">${esc(line)}</text>`)
    .join('');

  return `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="628" viewBox="0 0 1200 628">
  <rect width="1200" height="628" fill="#f8fafc" />
  <rect x="36" y="36" width="1128" height="556" rx="28" fill="#ffffff" stroke="#cbd5e1" stroke-width="2" />
  <rect x="60" y="60" width="1080" height="120" rx="20" fill="#0f172a" />
  <text x="90" y="120" fill="#f8fafc" font-size="24" font-family="Arial, sans-serif">${esc(input.subtitle)}</text>
  <text x="90" y="162" fill="#ffffff" font-size="42" font-weight="700" font-family="Arial, sans-serif">${esc(input.title)}</text>
  <text x="60" y="238" fill="#0f172a" font-size="34" font-weight="700" font-family="Arial, sans-serif">${esc(input.guestName)}</text>
  <text x="60" y="320" fill="#334155" font-size="24" font-family="Arial, sans-serif">${esc(input.eventName)}</text>
  ${body}
  <text x="60" y="566" fill="#64748b" font-size="20" font-family="Arial, sans-serif">Generated by EventFlow Pay Agent</text>
</svg>`.trim();
}
